#!/usr/bin/env node

/* command line interface for nextaur */

const program = require('commander');
const promptly = require('promptly');
const User = require('./server/user');
const db = require('./server/database');

let executed = false;

program
  .command('create-user <nick>')
  .alias('cu')
  .description('Create a new user')
  .action(async (nick) => {
    executed = true;

    let user = new User();
    try {
      await user.setNick(nick);
      let password = await promptly.password('Password: ', { replace: '*' });
      await user.setPassword(password);

      let passwordConfirm = await promptly.password('Confirm password: ', { replace: '*' });
      if (password !== passwordConfirm) { throw new Error("Passwords did not match!"); }

      await user.create();
      console.log("User was created successfully!");
    }
    catch (err) {
      console.log(`Error: ${err.message}`);
    }

    db.destroy();
  });

program
  .parse(process.argv);

if (!executed) {
  program.help();
}
